# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push txwifi
        run: |
          docker buildx build \
            --push \
            --tag ${{secrets.DOCKER_ORG}}/txwifi:latest \
            --tag ${{secrets.DOCKER_ORG}}/txwifi:${{env.tag}} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          readme-filepath: ./README.md
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_ORG }}/txwifi
